//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wROJA.StopsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stop", Namespace="http://schemas.datacontract.org/2004/07/wROJAServer.domain")]
    [System.SerializableAttribute()]
    public partial class Stop : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CommuneIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommuneNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RouteDetailsIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CommuneID {
            get {
                return this.CommuneIDField;
            }
            set {
                if ((this.CommuneIDField.Equals(value) != true)) {
                    this.CommuneIDField = value;
                    this.RaisePropertyChanged("CommuneID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommuneName {
            get {
                return this.CommuneNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CommuneNameField, value) != true)) {
                    this.CommuneNameField = value;
                    this.RaisePropertyChanged("CommuneName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RouteDetailsID {
            get {
                return this.RouteDetailsIDField;
            }
            set {
                if ((this.RouteDetailsIDField.Equals(value) != true)) {
                    this.RouteDetailsIDField = value;
                    this.RaisePropertyChanged("RouteDetailsID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StopsService.IStopsService")]
    public interface IStopsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStopsService/GetAllStops", ReplyAction="http://tempuri.org/IStopsService/GetAllStopsResponse")]
        wROJA.StopsService.Stop[] GetAllStops();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStopsService/GetAllStops", ReplyAction="http://tempuri.org/IStopsService/GetAllStopsResponse")]
        System.Threading.Tasks.Task<wROJA.StopsService.Stop[]> GetAllStopsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStopsServiceChannel : wROJA.StopsService.IStopsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StopsServiceClient : System.ServiceModel.ClientBase<wROJA.StopsService.IStopsService>, wROJA.StopsService.IStopsService {
        
        public StopsServiceClient() {
        }
        
        public StopsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StopsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StopsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StopsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public wROJA.StopsService.Stop[] GetAllStops() {
            return base.Channel.GetAllStops();
        }
        
        public System.Threading.Tasks.Task<wROJA.StopsService.Stop[]> GetAllStopsAsync() {
            return base.Channel.GetAllStopsAsync();
        }
    }
}
